// Generated by tools/vocab.js from schema/kernel-4.7 - do not edit by hand.

export const VOCAB = {
  resourceTypeGeneral: ["Audiovisual","Award","Book","BookChapter","Collection","ComputationalNotebook","ConferencePaper","ConferenceProceeding","DataPaper","Dataset","Dissertation","Event","Image","Instrument","InteractiveResource","Journal","JournalArticle","Model","OutputManagementPlan","PeerReview","PhysicalObject","Poster","Preprint","Presentation","Project","Report","Service","Software","Sound","Standard","StudyRegistration","Text","Workflow","Other"],
  titleType: ["AlternativeTitle","Subtitle","TranslatedTitle","Other"],
  contributorType: ["ContactPerson","DataCollector","DataCurator","DataManager","Distributor","Editor","HostingInstitution","Other","Producer","ProjectLeader","ProjectManager","ProjectMember","RegistrationAgency","RegistrationAuthority","RelatedPerson","ResearchGroup","RightsHolder","Researcher","Sponsor","Supervisor","Translator","WorkPackageLeader"],
  dateType: ["Accepted","Available","Collected","Copyrighted","Coverage","Created","Issued","Other","Submitted","Updated","Valid","Withdrawn"],
  relationType: ["IsCitedBy","Cites","IsSupplementTo","IsSupplementedBy","IsContinuedBy","Continues","IsNewVersionOf","IsPreviousVersionOf","IsPartOf","HasPart","IsPublishedIn","IsReferencedBy","References","IsDocumentedBy","Documents","IsCompiledBy","Compiles","IsVariantFormOf","IsOriginalFormOf","IsIdenticalTo","HasMetadata","IsMetadataFor","Reviews","IsReviewedBy","IsDerivedFrom","IsSourceOf","Describes","IsDescribedBy","HasVersion","IsVersionOf","Requires","IsRequiredBy","Obsoletes","IsObsoletedBy","Collects","IsCollectedBy","HasTranslation","IsTranslationOf","Other"],
  relatedIdentifierType: ["ARK","arXiv","bibcode","CSTR","DOI","EAN13","EISSN","Handle","IGSN","ISBN","ISSN","ISTC","LISSN","LSID","PMID","PURL","RAiD","RRID","SWHID","UPC","URL","URN","w3id"],
  descriptionType: ["Abstract","Methods","SeriesInformation","TableOfContents","TechnicalInfo","Other"],
  funderIdentifierType: ["ISNI","GRID","ROR","Crossref Funder ID","Other"],
  nameType: ["Organizational","Personal"],
  numberType: ["Article","Chapter","Report","Other"],
};

/** Identifier types that are not part of the schema but used in alternateIdentifier (free text). */
export const IDENTIFIER_TYPE_HINTS = VOCAB.relatedIdentifierType;
