// Local list of recurring people (data/Creators.json, generated by tools/people.js).
// Every entry names the registered DOIs it comes from; tools/people.js --verify checks them.
// It is searched before ORCID, which saves requests for the usual authors.

const fold = (s) =>
  String(s)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/ß/g, 'ss');

/** Loads the list; `readJson(path)` returns parsed JSON. */
export async function loadPeople(readJson, path = 'data/Creators.json') {
  const data = await readJson(path);
  return data.people ?? [];
}

/**
 * Searches name, given name, family name and ORCID iD. Every word of the input
 * has to match somewhere, so "carberry jos" finds "Carberry, Josiah".
 */
export function searchPeople(people, input, { limit = 10 } = {}) {
  const words = fold(input).split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  return people
    .filter((p) => {
      const haystack = fold(`${p.name} ${p.givenName} ${p.familyName} ${p.orcid}`);
      return words.every((w) => haystack.includes(w));
    })
    .slice(0, limit);
}

/** Converts a list entry into the model's creator/contributor fields. */
export const toPersonFields = (entry) => ({
  name: entry.name,
  givenName: entry.givenName,
  familyName: entry.familyName,
  nameType: entry.nameType ?? 'Personal',
  nameIdentifiers: entry.orcid
    ? [{ value: entry.orcid, nameIdentifierScheme: 'ORCID', schemeURI: entry.orcidSchemeURI ?? 'https://orcid.org' }]
    : [],
  affiliations: (entry.affiliations ?? []).map((a) => ({ ...a })),
});
