// Builds data/Creators.json from the fixtures: recurring people with an ORCID iD
// (public data). Values are unified per docs/mapping.md section 6: ORCID as a full URL,
// DZHW without the "(DZHW)" suffix, ROR schemeURI with a trailing slash.
//
// Every entry names the registered DOIs it was read from, and --verify asks DataCite whether
// each ORCID iD really appears in a findable record. Nothing is published that the database
// does not already show.
//
// Usage: node tools/people.js [--check | --verify]

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DOMParser, XMLSerializer } from '@xmldom/xmldom';
import { parse } from '../src/xml/parse.js';
import { idToUri, normalizeId } from '../src/api/orcid.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = 'data/Creators.json';

const ROR_SCHEME_URI = 'https://ror.org/';
const ORCID_SCHEME_URI = 'https://orcid.org';
const DZHW_ROR = 'https://ror.org/01n8j6z65';
const DZHW_NAME = 'German Centre for Higher Education Research and Science Studies';

const unifyAffiliation = (a) => {
  const name = a.name.replace(/\s*\(DZHW\)$/, '');
  const id = a.affiliationIdentifier || (name === DZHW_NAME ? DZHW_ROR : '');
  return id
    ? { name, affiliationIdentifier: id, affiliationIdentifierScheme: 'ROR', schemeURI: ROR_SCHEME_URI }
    : { name, affiliationIdentifier: '', affiliationIdentifierScheme: '', schemeURI: '' };
};

/** Collects people with an ORCID iD from all fixtures. */
export function collectPeople() {
  const dom = { DOMParser, XMLSerializer };
  const byOrcid = new Map();
  const files = readdirSync(join(ROOT, 'fixtures')).filter((f) => f.endsWith('.xml'));

  for (const file of files) {
    const { model } = parse(readFileSync(join(ROOT, 'fixtures', file), 'utf8'), dom);
    const source = model.identifier.value.trim().toLowerCase();
    for (const p of [...model.creators, ...model.contributors]) {
      const orcidId = p.nameIdentifiers
        .filter((n) => n.nameIdentifierScheme === 'ORCID')
        .map((n) => normalizeId(n.value))
        .find(Boolean);
      if (!orcidId || p.nameType === 'Organizational') continue;
      const entry = byOrcid.get(orcidId)
        ?? { orcid: idToUri(orcidId), variants: new Map(), affiliations: new Map(), sources: new Set() };
      if (source) entry.sources.add(source);
      const variant = JSON.stringify({ givenName: p.givenName, familyName: p.familyName });
      entry.variants.set(variant, (entry.variants.get(variant) ?? 0) + 1);
      for (const a of p.affiliations) {
        if (!a.name.trim()) continue;
        const unified = unifyAffiliation(a);
        entry.affiliations.set(unified.name, unified);
      }
      byOrcid.set(orcidId, entry);
    }
  }

  return [...byOrcid.values()]
    .map((e) => {
      // Fixtures disagree on some spellings; take the most frequent variant.
      const [variant] = [...e.variants.entries()].sort((a, b) => b[1] - a[1])[0];
      const { givenName, familyName } = JSON.parse(variant);
      return {
        name: `${familyName}, ${givenName}`,
        givenName,
        familyName,
        nameType: 'Personal',
        orcid: e.orcid,
        orcidSchemeURI: ORCID_SCHEME_URI,
        affiliations: [...e.affiliations.values()],
        sources: [...e.sources].sort(), // the registered DOIs this entry was read from
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name, 'de'));
}

export const build = () =>
  `${JSON.stringify({ source: 'fixtures/ (generated by tools/people.js)', people: collectPeople() }, null, 2)}\n`;

const DATACITE = 'https://api.datacite.org/dois';

/**
 * Asks DataCite whether this ORCID iD appears in a findable record, as creator or contributor.
 * Both notations have to be asked for: most records carry the bare iD, some the resolver URL
 * (10.21249/es:wps does), and the index matches the string as it was registered.
 */
export async function findableRecords(orcid, fetchImpl = fetch) {
  const id = normalizeId(orcid);
  const forms = `("${id}" OR "${idToUri(id)}")`;
  const query = `creators.nameIdentifiers.nameIdentifier:${forms} OR contributors.nameIdentifiers.nameIdentifier:${forms}`;
  const url = `${DATACITE}?query=${encodeURIComponent(query)}&page[size]=5&fields[dois]=doi,state`;
  const res = await fetchImpl(url, { headers: { Accept: 'application/vnd.api+json' } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const body = await res.json();
  return (body.data ?? []).filter((d) => d.attributes?.state === 'findable').map((d) => d.attributes.doi);
}

/** Checks every entry against DataCite; returns the number of entries without public proof. */
export async function verify(people, { fetchImpl = fetch, log = console.log } = {}) {
  let missing = 0;
  for (const person of people) {
    try {
      const dois = await findableRecords(person.orcid, fetchImpl);
      if (dois.length) {
        log(`  + ${person.name}: ${dois.length} findable record(s), e.g. ${dois[0]}`);
      } else {
        missing += 1;
        log(`  ! ${person.name} (${person.orcid}): no findable record carries this iD`);
      }
    } catch (e) {
      missing += 1;
      log(`  ? ${person.name} (${person.orcid}): not checked - ${e.message}`);
    }
  }
  return missing;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const generated = build();
  const path = join(ROOT, OUT);
  if (process.argv.includes('--verify')) {
    const people = JSON.parse(readFileSync(path, 'utf8')).people ?? [];
    console.log(`Checking ${people.length} entries against DataCite ...`);
    const missing = await verify(people);
    if (missing) {
      console.error(`${missing} entr(ies) without a public record - do not publish them.`);
      process.exit(1);
    }
    console.log('Every entry is backed by a findable DataCite record.');
  } else if (process.argv.includes('--check')) {
    const current = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
    if (current !== generated) {
      console.error(`${OUT} is out of date - run: node tools/people.js`);
      process.exit(1);
    }
    console.log(`${OUT} is up to date`);
  } else {
    writeFileSync(path, generated);
    console.log(`${OUT} written (${collectPeople().length} people)`);
  }
}
