// Generates src/model/vocab.js from the DataCite XSD, so the form's select options are
// never hand-maintained. Run: node tools/vocab.js [--check]
//
// --check exits non-zero when the generated file is out of date (used by the tests).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_DIR = 'schema/kernel-4.7';
const OUT = 'src/model/vocab.js';

// Model key -> include file holding the enumeration.
const LISTS = {
  resourceTypeGeneral: 'datacite-resourceType-v4.xsd',
  titleType: 'datacite-titleType-v4.xsd',
  contributorType: 'datacite-contributorType-v4.xsd',
  dateType: 'datacite-dateType-v4.xsd',
  relationType: 'datacite-relationType-v4.xsd',
  relatedIdentifierType: 'datacite-relatedIdentifierType-v4.xsd',
  descriptionType: 'datacite-descriptionType-v4.xsd',
  funderIdentifierType: 'datacite-funderIdentifierType-v4.xsd',
  nameType: 'datacite-nameType-v4.xsd',
  numberType: 'datacite-numberType-v4.xsd',
};

const values = (file) => [
  ...readFileSync(join(ROOT, SCHEMA_DIR, 'include', file), 'utf8').matchAll(/<xs:enumeration value="([^"]*)"/g),
].map((m) => m[1]);

export function build() {
  const entries = Object.entries(LISTS).map(([key, file]) => `  ${key}: ${JSON.stringify(values(file))},`);
  return [
    '// Generated by tools/vocab.js from ' + SCHEMA_DIR + ' - do not edit by hand.',
    '',
    'export const VOCAB = {',
    ...entries,
    '};',
    '',
    '/** Identifier types that are not part of the schema but used in alternateIdentifier (free text). */',
    'export const IDENTIFIER_TYPE_HINTS = VOCAB.relatedIdentifierType;',
    '',
  ].join('\n');
}

const generated = build();
const path = join(ROOT, OUT);
if (process.argv.includes('--check')) {
  const current = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
  if (current !== generated) {
    console.error(`${OUT} is out of date - run: node tools/vocab.js`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date`);
} else {
  writeFileSync(path, generated);
  console.log(`${OUT} written`);
}
